[sprite]
# sheet=""
# action=""
fps=8
opacity=1.0
visible=true
solid=true
always_on_top=true
scaling_type="Bilinear"

[animation]
play=true
rewind=false
frame=0

[location]
# x=0
# y=0

[size]
width=0.5
height=0.5

[reflection]
visible=true
padding=0.0
[reflection.fade]
height=0.65
opacity=0.25

[extensions]
enabled=[]
